--Setup the Role as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

--Setup the Warehouse as COMPUTE_WH

USE WAREHOUSE COMPUTE_WH;

--Create a new DATABASE

CREATE OR REPLACE DATABASE DEA_REAL_TIME_SCD1;

--Use the Database

USE DATABASE DEA_REAL_TIME_SCD1;


--Create RAW and TRANSFORMED Schema

CREATE OR REPLACE SCHEMA RAW;

CREATE OR REPLACE SCHEMA TRANSFORMED;


--Create a Storage Integration

CREATE OR REPLACE STORAGE INTEGRATION DEA_REAL_TIME_SCD1_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::919010206785:role/snowflake-s3-role'
STORAGE_ALLOWED_LOCATIONS = ('s3://real-time-scd1-data-bucket');--arn:aws:s3:::real-time-scd1-data-bucket

--Describe the Storage Integration

DESC INTEGRATION DEA_REAL_TIME_SCD1_INT;

 
--Create an External Stage
CREATE OR REPLACE STAGE DEA_REAL_TIME_SCD1.RAW.DEA_REAL_TIME_SCD1_STAGE
STORAGE_INTEGRATION = DEA_REAL_TIME_SCD1_INT
URL= 's3://real-time-scd1-data-bucket';


--Test the Integration
ls @DEA_REAL_TIME_SCD1.RAW.DEA_REAL_TIME_SCD1_STAGE;

USE DEA_REAL_TIME_SCD1.RAW;

CREATE TABLE DEA_REAL_TIME_SCD1.RAW.employee_raw
(json_data VARIANT);

CREATE OR REPLACE PIPE DEA_REAL_TIME_SCD1.RAW.employee_pipe
AUTO_INGEST=TRUE AS
COPY INTO DEA_REAL_TIME_SCD1.RAW.employee_raw
FROM @DEA_REAL_TIME_SCD1.RAW.DEA_REAL_TIME_SCD1_STAGE
FILE_FORMAT = (TYPE='JSON');

SHOW PIPES;

SELECT SYSTEM$PIPE_STATUS('DEA_REAL_TIME_SCD1.RAW.employee_pipe');

ALTER PIPE DEA_REAL_TIME_SCD1.RAW.employee_pipe SET PIPE_EXECUTION_PAUSED = true;

ALTER PIPE DEA_REAL_TIME_SCD1.RAW.employee_pipe SET PIPE_EXECUTION_PAUSED = false;

SELECT * FROM DEA_REAL_TIME_SCD1.RAW.employee_raw;

